# Generated by Django 4.2.16 on 2024-11-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("deadline", models.DateTimeField()),
                ("priority", models.IntegerField()),
                ("estimatedDuration", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("completed", models.BooleanField()),
                ("feedback", models.TextField()),
                (
                    "subTasks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.todo"
                    ),
                ),
                ("tags", models.ManyToManyField(to="api.tag")),
            ],
        ),
    ]
