# Generated by Django 4.2.16 on 2024-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_habitsummary_schedule_todosummary_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="plan",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="estimatedDuration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="feedback",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(null=True),
        ),
    ]
