# Generated by Django 4.2.16 on 2024-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_habit_tags_remove_todo_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="estimatedDuration",
            field=models.CharField(blank=True, default="", max_length=128),
            preserve_default=False,
        ),
    ]
