# Generated by Django 4.2.16 on 2024-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_schedule_date_alter_todo_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtodo",
            name="estimatedDuration",
            field=models.CharField(blank=True, default="", max_length=128),
            preserve_default=False,
        ),
    ]
